// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKlGCYI_69qCrsSgBnTYv69znlh0t2b9U',
    appId: '1:92093430450:web:e1c765a0656ead8b31a7ab',
    messagingSenderId: '92093430450',
    projectId: 'pm-corte2',
    authDomain: 'pm-corte2.firebaseapp.com',
    storageBucket: 'pm-corte2.appspot.com',
    measurementId: 'G-VH6T6B8Z44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvjdhytgL-lGOfjC073G29-YgQswE-v3I',
    appId: '1:92093430450:android:19b4dd9ec151b08231a7ab',
    messagingSenderId: '92093430450',
    projectId: 'pm-corte2',
    storageBucket: 'pm-corte2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKtScOjJHK6wXXxMaA--DKG05eZv59dTU',
    appId: '1:92093430450:ios:6098c0a0dbe0a50331a7ab',
    messagingSenderId: '92093430450',
    projectId: 'pm-corte2',
    storageBucket: 'pm-corte2.appspot.com',
    androidClientId: '92093430450-2h10f0n2khd439ae2bhdoa3fmmbqruaq.apps.googleusercontent.com',
    iosClientId: '92093430450-9die7o9njkl42oif3c0i7faae1cqd0kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKtScOjJHK6wXXxMaA--DKG05eZv59dTU',
    appId: '1:92093430450:ios:6098c0a0dbe0a50331a7ab',
    messagingSenderId: '92093430450',
    projectId: 'pm-corte2',
    storageBucket: 'pm-corte2.appspot.com',
    androidClientId: '92093430450-2h10f0n2khd439ae2bhdoa3fmmbqruaq.apps.googleusercontent.com',
    iosClientId: '92093430450-9die7o9njkl42oif3c0i7faae1cqd0kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );
}
